### PR TITLE
Fix os.epoch("ingame") throwing "Unsupported operation"

### LINKED ISSUE #123: `os.epoch("ingame")` errors with `Unsupported operation`
### Minecraft Version

1.18.x

### Version

1.100.8

### Details

The [CC:Tweaked docs](https://tweaked.cc/module/os.html#v:epoch) lists `"ingame"`, `"utc"`, and `"local"` as valid argument values. However, `os.epoch("ingame")` results in an error, `"Unsupported operation"`.

### PR DESCRIPTION
**Pull request by toad-dev**
Fixes #123

The issue was just the result of some sort of find and replace error.

### CODE REVIEW

**Comment by SquidDev** [comment]
https://github.com/cc-tweaked/CC-Tweaked/commit/69b211b4fbaf3fad33025fb385de51a4607168aa I think it needs patching in a few more places.

**Comment by toad-dev** [comment]
Ah, thank you! I should've looked into the git history first.

**Comment by Merith-TK** [comment]
is this mergable or is it stale?

**Comment by SquidDev** [comment]
Mergable.

**Comment by Merith-TK** [comment]
Aight, not in an position to merge at the moment, feel free to merge at
your discretion

**Pull request merged**
