### PR TITLE
Resolve issue #16 for cc-restitched, center printout in item frame, and fix page flipping for prints.

### PR DESCRIPTION
**Pull request by coolsa**
Made a few fixes in this PR, mainly:
- Centred printouts a bit better.
- Printout page turning fixed, was an unreported bug.
- Custom server terminal dimensions now render on client, resolving issue #16.

### CODE REVIEW

**Comment by toad-dev** [comment]
Are the printouts off center? It looks like these changes make it worse:
printouts

**Comment by coolsa** [comment]
> Are the printouts off center? It looks like these changes make it worse: printouts

Oops, should have tested with a fully filled page. In an item frame, the right side is slightly exposed, which is what I was trying to resolve, can't believe I missed moving the text too.

**Comment by toad-dev** [comment]
Here is a patch that centers the printouts:
```patch
diff --git a/src/main/java/dan200/computercraft/client/render/ItemPrintoutRenderer.java b/src/main/java/dan200/computercraft/client/render/ItemPrintoutRenderer.java
index 8b0e7cf8..8d07b890 100644
--- a/src/main/java/dan200/computercraft/client/render/ItemPrintoutRenderer.java
+++ b/src/main/java/dan200/computercraft/client/render/ItemPrintoutRenderer.java
@@ -63,7 +63,7 @@ public final class ItemPrintoutRenderer extends ItemMapLikeRenderer
         double height = LINES_PER_PAGE * FONT_HEIGHT + Y_TEXT_MARGIN * 2;
 
         // Non-books will be left aligned
-        if( !book ) width += offsetAt( pages );
+        if( !book ) width += offsetAt( pages - 1 );
 
         double visualWidth = width, visualHeight = height;
 
diff --git a/src/main/java/dan200/computercraft/client/render/PrintoutRenderer.java b/src/main/java/dan200/computercraft/client/render/PrintoutRenderer.java
index 33a13eac..9912cc63 100644
--- a/src/main/java/dan200/computercraft/client/render/PrintoutRenderer.java
+++ b/src/main/java/dan200/computercraft/client/render/PrintoutRenderer.java
@@ -32,12 +32,12 @@ public final class PrintoutRenderer
     /**
      * Padding between the left and right of a page and the text.
      */
-    public static final int X_TEXT_MARGIN = 13;
+    public static final int X_TEXT_MARGIN = 11;
 
     /**
      * Padding between the top and bottom of a page and the text.
      */
-    public static final int Y_TEXT_MARGIN = 11;
+    public static final int Y_TEXT_MARGIN = 10;
 
     /**
      * Width of the extra page texture.

```
The margin constants were slightly off, and there was an off-by-one error adding an extra bit of offset. Can you revert all the changes related to this and implement this patch instead? I would prefer to solve it this way rather than adding a magic number to every position.

Thank you for catching to page turning bug too!

As for #16, I will need more time to review that code. A separate PR with those changes would help.

**Comment by coolsa** [comment]
Thank you for the fix, I've gone and changed the relevant files, much more elegant than what I had done. I'll go ahead and open up a seperate PR for the other issue too.

**Pull request merged**
