### PR TITLE
Merge upstream

### LINKED ISSUE #121: Putting shulkers in shulkers
### Minecraft Version

1.19.x

### Version

1.101.0

### Details

Using the [peripheral inventory api](https://tweaked.cc/generic_peripheral/inventory.html) it's possible to move a shulker box into another shulker box.

### LINKED ISSUE #122: Items disappearing when transferred from furnace output to full inventory
### Minecraft Version

1.18.x

### Version

1.100.8

### Details

I have a system that transfers items from a furnace output slot to a barrel. When the barrel is full items will disappear instead of staying in the furnace.
The issue is not specific to barrels, it also happens with chests

Steps to recreate:
1. Create at wired network containing a furnace, a computer and a barrel 

3. Block the barrel with an item
image
4. Smelt some items in the furnace
image
5. Run this program:
```
barrel = peripheral.find("minecraft:barrel")
furnace = peripheral.find("minecraft:furnace")
print(furnace.pushItems(peripheral.getName(barrel), 3))
```
6. All the items from the output slot will disappear 

Other observations:
If there is some but not enough space in the target inventory it will fill the inventory and the remaining items will disappear.
The pushItems function returns the amount of items successfully moved, the disappeared items are not counted.
If a limit is set in the pushItems function only the amount of items specified will disappear.

### LINKED ISSUE #133: Quilt will have MixinLanguage
https://github.com/QuiltMC/quilt-standard-libraries/pull/229

### PR DESCRIPTION
**Pull request by SquidDev**
Yeah, I don't really know how to write a description for this. This pulls in the work on making CC:T multi-loader compatible, which should make it easier to keep CC:R in sync with CC:T in the future.

Fixes #121, Fixes #122, Closes #133. Should also resolve some of the other issues (#130), but I'm less confident there.

### CODE REVIEW

**Comment by Merith-TK** [comment]
I assume this is just for 1.19 and wont be expecting an 1.18 equivalent? I would like to keep 1.18 CC:R maintained atleast until 1.20 is released if possible...

**Comment by SquidDev** [comment]
> I assume this is just for 1.19 and wont be expecting an 1.18 equivalent? 

Correct. It's got a lot of API breaking changes in (hence doing it now, after 1.19.3 has already broken everything), so it's not really viable to backport any of this.

**Comment by Merith-TK** [comment]
I assume this has been *somewhat* tested on fabric/quilt?

**Comment by SquidDev** [comment]
Yep. All the game tests now run on Fabric too, but I've a friend running this on a private server for a few weeks. I'm sure there are _some_ bugs which haven't surfaced, but it should be pretty solid.

**Comment by Merith-TK** [comment]
GH Actions have not produced an build, nor can I build in Gitpod, if you could look into that, I gotta head to work atm.

**Comment by SquidDev** [comment]
Fixed! I forgot to update the path to the upload task in GH.

**Comment by Patbox** [comment]
Looking that CC:T's repo also has fabric related code now, does it make sense to maintain it in two repos? 

Other thing is it looks like it lost support for Common Protection API on fabric

**Comment by Merith-TK** [comment]
Currently with CC:R's goal of maintaining parity, merging the repos into
one repo for development doesn't seem like that bad of an idea.

Problem is I don't know if the dev environments are 100% compatible between
the two (for example. Can one compile the fabric code from the current
forge repo or vice-versa?)

If we can manage that then merging the repos into one seems like an
acceptable possibility

**Comment by Patbox** [comment]
It should from what I've quickly checked the repo, since it is some multiloader setup (similar to one used by botania for example)

**Comment by SquidDev** [comment]
> Looking that CC:T's repo also has fabric related code now, does it make sense to maintain it in two repos?

While I would definitely appreciate bug fixes being submitted upstream, I still think it makes sense for CC:R to be its own project. CC:R has got its own changes (i.e. new textures!) and general "feel" which I think merit it being its own thing.

The multi-loader work was very much done to make it easier to keep the two mods in sync (especially in the API, which has diverged over the last few MC versions), rather than merge the mods themselves.

> Other thing is it looks like it lost support for Common Protection API on fabric

We now fire all the appropriate Fabric interaction events, so this should work by default with claim mods. I'd also expect #114 and #115 to be fixed, though I haven't checked yet.

**Comment by Merith-TK** [comment]
> "Add back the netherite pickaxe"

Ah yes, the tool that got added on accident and serves no purpose other
than to flex that you have enough netherite that you can spend it on an
turtle.
And don't forget it was netherite tools, plural lol

Honestly I was think if the mods got merged into one repo, you could do
what we have done for the classic textures. But for the fabric. And just
label them "Restitched" and "Tweaked" respectively, and default to either
depending on modloader.

**Comment by Patbox** [comment]
Yep that sounds like good solution

**Comment by Merith-TK** [comment]
I see you made a datapack, the main reason why I was saying the specific tools that CC:R has is because in all regards except netherite tool's on turtles, you can take an world that only has CC:T/R on it, and take it to the other loader, so worlds that use computercraft for map making (and create worlds) can be ported over to fabric or forge without issue outside of loader specific issues with the mods (more recently this should be fixed in both mods stated)

**Comment by SquidDev** [comment]
Ahh, that was in response to https://github.com/cc-tweaked/CC-Tweaked/issues/1254 rather than CC:R specifically.

**Comment by SquidDev** [comment]
I think this PR is stalled but, as people are using CC:T for Fabric more than I'd like, would quite like to get some resolution here.

The main problem as it currently stands is that CC:T for Fabric and CC:R's APIs are incompatible, due to drift over the last year. While worlds are compatible between the two - peripheral mods which target one will crash on the other.

I think there's a matrix of options here:
 - For Minecraft versions, we can either change this for 1.19.3 (breaking existing peripheral mods, though I don't think there's too many) or wait until 1.20.
 - For CC:T vs CC:R, I think we either merge this PR (and then keep the two mods in sync) or just kill off CC:R. Optionally unpublishing the current 1.19.3 CC:R version if we decided to do this now.

**Comment by Merith-TK** [comment]
Personally since CC:T is officially going multiloader fabric. I am for depreciation of CC:R in favor of CC:T, especially with the API Drift due to the main goal of CC:R being 1:1 parity with CC:T, (Outside of textures and the aforementioned Netherite Tool turtles. Of which I'm still trying to figure out when the fuck those got added)

**Comment by Patbox** [comment]
Yeah, deprecating CC:R makes sense. Through without unpublishing of current ver and only with a "redirect"

**Comment by Patbox** [comment]
Alternatively we can wait for 1.19.4, but who knows when it releases

**Comment by SquidDev** [comment]
> Alternatively we can wait for 1.19.4, but who knows when it releases

Yep, happy to go that route!

**Comment by SquidDev** [comment]
As agreed above, CC:T for 1.19.4 publishes Fabric jars as well as Forge ones (see https://github.com/cc-tweaked/CC-Tweaked/commit/266182996da07d9b4535479e1b6b896ff8682820), so closing this.

**Comment by Merith-TK** [comment]
honestly having one final release for CC:R (an 1.18.2 and 1.19.2/3 release) of the latest update wouldn't be a bad idea in my opinion, would allow resolving a few final bugs.

assuming CC:T's official fabric work wont get backported that is. if it does get backported that would also be great

**Comment by SquidDev** [comment]
> assuming CC:T's official fabric work wont get backported

Yeah, correct. The multi-loader work was a massive piece of work, I have no wish to do it again :).

**Comment by Merith-TK** [comment]
I mean in *theory* it should be as simple as backporting the code a bit, same way you would get normal code to back port *but*, I can see why one would say no on that front :)

**Pull request closed without merging**
